web:
  image: nginx:1.9.9
  ports:
    - 8080:80
  volumes:
    - ./:/var/www/php-app
    - ./nginx.conf:/etc/nginx/nginx.conf
  links:
    - php
php:
  image: php:7.0.1-fpm
  volumes:
    - ./:/var/www/php-app
  links:
    - db
db:
  image: mysql:5.7.10
  ports:
    - 33060:3306
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes